[package]
name = "mopsorez_telegram_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
env = "1.0.1"
reqwest = { version = "0.12.23", features = ["json"] }
serde_json = "1.0.143"
serial_test = "3.2.0"
teloxide = "0.17.0"
tokio = { version = "1.47.1", features = ["full"] }
